### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by dadexix86** [mandel-macaque/chancho#119]
Hello,
After the last update it does not start anymore on my bq device.
It keeps charging and charging (the rolling Ubuntu logo) but does never start.

Interrupting the charging (left swipe, right swipe, up swipe to close the app) and trying again does not sove.

**Comment by dadexix86** [comment]
Rebooting solved the problem.

**Comment by mandel-macaque** [comment]
Looks like there is an issue in some cases with the update of the .desktop file in the ubuntu app scope. The .desktop does not get update in the scope and the system tries to start the old version of the application. 

I'll talk with the guys that mantain the scope to see if there is a way to solve this, else in some cases the application will have this issue. Kind of a PITA.
