### ISSUE TITLE
Removing all categories at initial setup, unable to add new income

### ISSUE THREAD

**Issue by sdrmlm** [mandel-macaque/chancho#124]
Removing all categories at the initial setup does not produce a warning like the one that is produced when attempting to do the same after the initial setup.

After all categories had been removed, all new categories I created became Expenses, I could not add a new Income category.

**Comment by mandel-macaque** [comment]
Oh! thx for the bug report! Will look into that (Sorry f or the delay, I was on holidays)

**Comment by mandel-macaque** [comment]
Fix has been merged. A new release will be done soon.

**Comment by mandel-macaque** [comment]
The new version is in the store, ook for version 0.1.13
