### ISSUE TITLE
Use the "tick" icon when saving the contents of a bottom edge page

### ISSUE THREAD

**Issue by dplanella** [mandel-macaque/chancho#153]
- On the Bills tab, when adding a new entry via the bottom edge, the icon on the top right hand side corner to confirm the entry, is a plus sign, which leads me to believe that it will take me to "add" yet something else, rather than just confirming and saving.
- On the Accounts tab, it's the same situation to add a new account.
- On the Edit account page, the icon used is the "Edit" one, which then leads me to believe that there are more things to edit once I've pressed it.

I would suggest using consistently a tick icon to indicate confirmation rather than further actions, in the same way the Contacts app does when adding a new contact from the bottom edge. The Clock app, with the bottom edge to add a new alarm, is a good example of a pattern showing when to use the "plus" sign icon vs. the "tick" one.

**Comment by mandel-macaque** [comment]
You have a valid point, we need to be consistent. Changing the icon is a no brainer so I'm happy to accept the bug. I'm planning (once recurrent transactions have been finished) to move to the new List items and add the actions there, in that case everything will be much more understandable to the user.

**Comment by mandel-macaque** [comment]
I'm going to change the icons as follows:

* Use the ok icon (tick) in all those pages when you add a new item, that is, nea account, new category and new transaction.
* I'm leaving the edit icon as a confirmation to edit it. I know if might be confusing but this is a temp fix before we move to the new list items (where edit/delete) will not be in the page as actions.

I hope it is an improvement.
