### ISSUE TITLE
Allow editing entries from previous month

### ISSUE THREAD

**Issue by danjjl** [mandel-macaque/chancho#155]
It would be nice if Chancho allowed editing entries from previous months.

On the Bills page, clicking on the month would open the month and year selector (like in the Stats page).

**Comment by mandel-macaque** [comment]
Hello,

It already does. Select the date, change the month and edit the transaction.

Regards,

Manuel

**Comment by danjjl** [comment]
Oups you are right  :)

For an unknown reason it is a bit less responsive then on the Stats page.

So I would click on the month twice which would hide the dialogue box before it even showed on the screen.

**Comment by mandel-macaque** [comment]
Hmmmmm we migth have a performance bug I have to look into.. Ill try to
corfirm it.

**Comment by M1dgard** [comment]
I came here to report the same bug. It is not so obvious, I tried swiping everything and clicking everywhere, but the month selector opens too slow to detect it.

**Comment by mandel-macaque** [comment]
I need to improve the initial boot to show that feature..  I wonder if
adding a hint is a good idea,  or making it a button..
