### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Vostro162** [mandel-macaque/chancho#156]
hi, here is a German Translation :D 
https://gist.github.com/Vostro162/499b777c737d82d39b30

**Comment by mandel-macaque** [comment]
AWESOME! Will land this today, thx.

**Comment by mandel-macaque** [comment]
FYI there is a pull request with your changes here => https://github.com/mandel-macaque/chancho/pull/157 

If the test pass etc.. I'll build the package and will publish the app.

**Comment by mandel-macaque** [comment]
Everything looks good.
