### ISSUE TITLE
Invoices and statistics show the same view

### ISSUE THREAD

**Issue by BigButt** [mandel-macaque/chancho#161]
They show an empty September because I submitted my bills to the past.
I can't change anything in it.

**Comment by mandel-macaque** [comment]
Hello!

You just need to click in the month label and change it to point to the one you are interested in, here is an example:

https://www.youtube.com/watch?v=b8FGPGdHApk

I hope it helps.

**Comment by mandel-macaque** [comment]
I forgot to mention, they show the same "view" because they are both empty :)
